#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
from pathlib import Path
import os
from models.qr import Qr
from funciones import scale
# generated by wxGlade 1.0.2 on Fri Nov 26 12:16:45 2021
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: Principal.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.scale = scale()
		self.qrFormat = ["svg" , "png"]
#usuario de windows y Documents
		self.path_dir = Path(Path.home(),"Documents","ISA_qrGenerator")



		self.SetSize((400, 300))
		self.SetTitle(_("ISA QrGenerator 0.1"))

		self.panel_1 = wx.Panel(self, wx.ID_ANY)

		sz_principal = wx.BoxSizer(wx.VERTICAL)

		lb_site = wx.StaticText(self.panel_1, wx.ID_ANY, _("ingrese web&w"))
		sz_principal.Add(lb_site, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

		self.txt_site = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
		sz_principal.Add(self.txt_site, 0, 0, 0)

		lb_name = wx.StaticText(self.panel_1, wx.ID_ANY, _("nombre del archivo salida"))
		sz_principal.Add(lb_name, 0, wx.EXPAND, 0)

		self.txt_name = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
		sz_principal.Add(self.txt_name, 0, wx.EXPAND, 0)

		lb_scale = wx.StaticText(self.panel_1, wx.ID_ANY, _("Escala"))
		sz_principal.Add(lb_scale, 0, wx.EXPAND, 0)

		self.cb_scale = wx.ComboBox(self.panel_1, wx.ID_ANY, choices= self.scale, style=wx.CB_DROPDOWN)
		sz_principal.Add(self.cb_scale, 0, 0, 0)
		self.cb_scale.SetSelection(0)

		lb_formato = wx.StaticText(self.panel_1, wx.ID_ANY, _("formato"))
		sz_principal.Add(lb_formato, 0, wx.EXPAND, 0)

		self.cb_format = wx.ComboBox(self.panel_1, wx.ID_ANY, choices= self.qrFormat, style=wx.CB_DROPDOWN)
		sz_principal.Add(self.cb_format, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		self.cb_format.SetSelection(0)
		# self.chk_directorio = wx.CheckBox(self.panel_1, wx.ID_ANY, self.path_dir)
		# self.chk_directorio = wx.CheckListBox(self.panel_1, wx.ID_ANY, choices=[("elija carpeta de destino"),(self.path_dir)])
		# self.chk_directorio.SetSelection(0)
		# sz_principal.Add(self.chk_directorio, 0, wx.EXPAND, 0)

		sz_botones = wx.BoxSizer(wx.HORIZONTAL)
		sz_principal.Add(sz_botones, 1, wx.EXPAND, 0)
		
		self.btn_generar = wx.Button(self.panel_1, wx.ID_ANY, _("Generar&G "))
		sz_botones.Add(self.btn_generar, 0, wx.BOTTOM, 0)

		self.btn_abrir = wx.Button(self.panel_1, wx.ID_ANY, _("Abrir carpeta&A"))
		sz_botones.Add(self.btn_abrir, 0, 0, 0)

		self.panel_1.SetSizer(sz_principal)

		self.Layout()
		self.Centre()
		# self.Bind(wx.EVT_CHECKBOX, self.folder)
		self.btn_generar.Bind(wx.EVT_BUTTON,self.generar)
		self.btn_abrir.Bind(wx.EVT_BUTTON,self.download)
		# self.chk_directorio.Bind(wx.EVT_BUTTON,self.folder)


	


	def generar(self , event):
	#valores de los controles
		site=self.txt_site.GetValue()
		name= self.txt_name.GetValue()
		scale = self.cb_scale.GetValue()
		qrFormat = self.cb_format.GetValue()
		if  not os.path.exists(self.path_dir):
			os.makedirs(self.path_dir)
			path = self.path_dir
		else:

			path=self.path_dir
		if site and name != "": 
			qr = Qr(site , name , scale,qrFormat,path)
		
			qrcd = qr.generate_qr() 
			if qrFormat=="svg":
				qr.save(qrcd)
			elif qrFormat=="png":
				qr.save_png(qrcd)
			dialogo = wx.MessageDialog(self, 'QR Generado exitosamente!.Desea abrir la carpeta donde se  generó', 'confirmar', wx.YES_NO | wx.NO_DEFAULT)
			if dialogo.ShowModal() == wx.ID_YES:
				downloads(self)
		else:
			error=wx.MessageDialog(self, "los campos no se pueden dejar bacíos.", "error")
			error.ShowModal()



	def folder(self , event):
		dlgFol = wx.DirDialog(self, "seleccione carpeta")
		if dlgFol.ShowModal() == wx.ID_OK:
			self.path_dir= dlgFol.GetPath()
			self.chk_directorio.SetValue(self.path_dir)
		dlgFol.Destroy

#
	def download(self , event):
		path=self.path_dir
		os.system(f'start {os.path.realpath(path)}')


	
def downloads(self ):
		path=self.path_dir
		os.system(f'start {os.path.realpath(path)}')

	
		# end wxGlade



# end of class Principal

class MyApp(wx.App):
	def OnInit(self):
		self.frame = Principal(None, wx.ID_ANY, "")
		self.SetTopWindow(self.frame)
		self.frame.Show()
		return True

# end of class MyApp

if __name__ == "__main__":
	gettext.install("app") # replace with the appropriate catalog name

	app = MyApp(0)
	app.MainLoop()
